// ============================================================
// FIREBASE CONFIGURATION PLACEHOLDER
// Replace this file with your actual firebase_options.dart
// generated by: flutterfire configure
// ============================================================
// 
// Steps to configure Firebase:
// 1. Create a Firebase project at console.firebase.google.com
// 2. Enable Authentication (Email/Password) and Realtime Database
// 3. Run: dart pub global activate flutterfire_cli
// 4. Run: flutterfire configure
// This will generate the real firebase_options.dart
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-IJHbhjOlENdbP9viDxEumIgjJMtJJTM',
    appId: '1:530603219844:android:712c94491b832702c4dbd1',
    messagingSenderId: '530603219844',
    projectId: 'harbr-3cd5c',
    databaseURL: 'https://harbr-3cd5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'harbr-3cd5c.firebasestorage.app',
  );

  // ⚠️  REPLACE these placeholder values with your actual Firebase config!

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNrIaJB7dQ9YzdHdCSI6UJMuIKaXwjgFk',
    appId: '1:530603219844:ios:009a0a2dbb85d2eac4dbd1',
    messagingSenderId: '530603219844',
    projectId: 'harbr-3cd5c',
    databaseURL: 'https://harbr-3cd5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'harbr-3cd5c.firebasestorage.app',
    iosBundleId: 'com.harbr.harbr',
  );

}